[package]
name = "rust_kernel"
version = "0.1.0"
edition = "2021"

[lib]
name = "rust_kernel"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.22", features = ["extension-module"] }

[package.metadata.maturin]
name = "rust_kernel"